CREATE DATABASE DELIVERY_TIME_ANALYSIS;
USE DELIVERY_TIME_ANALYSIS;
SELECT * FROM ZOMATO_SALES;

-- 1.WHAT IS THE IMPACT ON DELIVERY TIME IF THERE ARE WEATHER AND TRAFFIC PROBLEMS?
SELECT Weather, Traffic_Level, AVG(Delivery_Time_min) AS AVG_DELIVERY_TIME FROM ZOMATO_SALES 
GROUP BY  Weather, Traffic_Level ORDER BY AVG_DELIVERY_TIME DESC;

-- 2.AVERAGED DELIVERY TIME BASED UPON THEIR COURIER EXPERIENCE YEARS.
SELECT  Courier_Experience_yrs, AVG(Delivery_Time_min) AS AVG_DELIVERY_TIME FROM ZOMATO_SALES
GROUP BY Courier_Experience_yrs ORDER BY Courier_Experience_yrs DESC;

-- 3.
SELECT Time_of_Day, AVG(Preparation_Time_min) AS AVG_PREPARATION_TIME, AVG(Delivery_Time_min) AS AVG_TOTAL_DELIVERY_TIME FROM ZOMATO_SALES
GROUP BY Time_of_Day ORDER BY AVG_TOTAL_DELIVERY_TIME DESC;
